name: Mint tests
on:
  push:
    branches:
       - 'master'
  pull_request:
      branches:
        - 'master'

jobs:
    test-container:
        runs-on: ubuntu-latest
        container:
            image: node:10.11.0-alpine

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
